FROM golang:alpine

# Set working directory
WORKDIR /manuka-listener

# Copy project files for build
COPY . .

RUN sed -i 's/http\:\/\/dl-cdn.alpinelinux.org/https\:\/\/alpine.global.ssl.fastly.net/g' /etc/apk/repositories

# Install dependencies
RUN apk add --no-cache git
RUN go get github.com/githubnemo/CompileDaemon

# Build server
RUN go build

# Run server
CMD ["CompileDaemon", "-command", "/manuka-listener/manuka-listener"]